-- vim.pack.add({
-- 	{ src = "https://github.com/idelice/nvim-jls" },
-- })
--
-- require("jls").setup({
-- 	jls_dir = vim.fn.expand("~/.jls"),
-- 	filetypes = { "java" },
-- 	root_markers = {
-- 		"settings.gradle",
-- 		"settings.gradle.kts",
-- 		--"pom.xml",
-- 		--"build.gradle",
-- 		--"build.gradle.kts",
-- 		--"WORKSPACE",
-- 		--"WORKSPACE.bazel",
-- 		--".java-version",
-- 		".git",
-- 	},
-- 	settings = { -- LSP settings (sent via didChangeConfiguration)
-- 		jls = {
-- 			diagnostics = {
-- 				enable = true,
-- 				unusedImports = "warning", -- "error" | "warning" | "off"
-- 			},
-- 			features = {
-- 				inlayHints = true,
-- 				semanticTokens = true,
-- 			},
-- 		},
-- 	},
-- 	init_options = {},
-- 	env = {}, -- extra environment variables
-- 	java_home = vim.fn.expand("~/.sdkman/candidates/java/21.0.9-tem"), -- sets JAVA_HOME for the server
-- 	lombok = { path = nil, javaagent = nil }, -- If omitted, the plugin tries to auto-detect Lombok from ~/.m2 first, then from any lombok.search_paths.
-- 	extra_args = {}, -- extra args passed to JLS launcher
-- 	status = { enable = true, notify = false }, -- progress status
-- 	codelens = { enable = false }, -- auto-refresh codelens on BufEnter
-- })
