[manager]
marker_copied = { fg = "#98BC6D", bg = "#98BC6D" }
marker_cut = { fg = "#E46A78", bg = "#E46A78" }
marker_marked = { fg = "#957FB8", bg = "#957FB8" }
marker_selected = { fg = "#E5C283", bg = "#E5C283" }

cwd = { fg = "#E5C283" }
hovered = { reversed = true }
preview_hovered = { reversed = true }

find_keyword = { fg = "#E5C283", bg = "#1F1F28" }
find_position = {}

tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

count_copied = { fg = "#1F1F28", bg = "#98BC6D" }
count_cut = { fg = "#1F1F28", bg = "#E46A78" }
count_selected = { fg = "#1F1F28", bg = "#E5C283" }

border_symbol = "│"
border_style = { fg = "#DDD8BB" }


[mode]
normal_main = { fg = "#1F1F28", bg = "#7EB3C9" }
normal_alt = { fg = "#7EB3C9", bg = "#1F1F28" }
select_main = { fg = "#1F1F28", bg = "#957FB8" }
select_alt = { fg = "#957FB8", bg = "#1F1F28" }
unset_main = { fg = "#1F1F28", bg = "#E5C283" }
unset_alt = { fg = "#E5C283", bg = "#1F1F28" }


[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "#DDD8BB", bg = "#1F1F28" }

progress_label = { fg = "#7EB3C9", bg = "#1F1F28", bold = true }
progress_normal = { fg = "#1F1F28", bg = "#1F1F28" }
progress_error = { fg = "#1F1F28", bg = "#1F1F28" }

perm_type = { fg = "#98BC6D" }
perm_read = { fg = "#E5C283" }
perm_write = { fg = "#E46A78" }
perm_exec = { fg = "#7EB3C9" }
perm_sep = { fg = "#957FB8" }


[pick]
border = { fg = "#7EB3C9" }
active = { fg = "#957FB8", bold = true }
inactive = {}

[input]
border = { fg = "#7EB3C9" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "#7EB3C9" }
active = { reversed = true }
inactive = {}

[tasks]
border = { fg = "#7EB3C9" }
title = {}
hovered = { fg = "#957FB8" }

[which]
cols = 2
separator = " - "
separator_style = { fg = "#A8A48D" }
mask = { bg = "#1F1F28" }
rest = { fg = "#A8A48D" }
cand = { fg = "#7EB3C9" }
desc = { fg = "#DDD8BB" }

[help]
on = { fg = "#7EB3C9" }
run = { fg = "#957FB8" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#1F1F28", bg = "#DDD8BB" }

[notify]
title_info = { fg = "#98BC6D" }
title_warn = { fg = "#E5C283" }
title_error = { fg = "#E46A78" }

[filetype]
rules = [
  # images
  { mime = "image/*", fg = "#E5C283" },

  # media
  { mime = "{audio,video}/*", fg = "#957FB8" },

  # archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#E46A78" },

  # documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#A98FD2" },

  # broken links
  { url = "*", is = "orphan", fg = "#E46A78" },

  # executables
  { url = "*", is = "exec", fg = "#7EB3C9" },

  # fallback
  { url = "*", fg = "#DDD8BB" },
  { url = "*/", fg = "#7EB3C9" },
]
