unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g prefix C-w

set -g mouse on

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes using [v] and [h]
unbind '"'
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Kill pane using [x]
bind x kill-pane

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended

# vim-tmux-navigator
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# tmux colorscheme
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @minimal-tmux-status "top"
set -g @minimal-tmux-justify "left"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
