# --- Font ---
font_family Sarasa Term K
symbol_map U+E000-U+E00D,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E62B,U+E700-U+E7C5,U+F000-U+F2E0,U+F300-U+F31C,U+F400-U+F4A8,U+F500-U+F8FF,U+F0001-U+F1AF0 JetBrainsMono Nerd Font Mono
bold_font auto
italic_font	auto
bold_italic_font auto
font_size 15
modify_font underline_position 3
modify_font cell_width 90%
modify_font cell_height	6
modify_font baseline 1

# --- macOS Option as Alt (for nvim keybindings) ---
macos_option_as_alt both

# --- Appearance ---
include themes/kanagawabones.conf
macos_titlebar_color background
window_title_format "🐱"
window_padding_width 8
macos_show_window_title_in window
allow_remote_control no

# --- Splits & Layouts ---
enabled_layouts splits,stack

# Splits
map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current
map alt+x close_window

# Move
map alt+cmd+h neighboring_window left
map alt+cmd+j neighboring_window bottom
map alt+cmd+k neighboring_window top
map alt+cmd+l neighboring_window right

# Size 
map cmd+ctrl+left  resize_window narrower 10
map cmd+ctrl+down  resize_window shorter 10
map cmd+ctrl+up    resize_window taller 10
map cmd+ctrl+right resize_window wider 10

# Tab
map cmd+t new_tab
map alt+n next_tab
map alt+p previous_tab

# Inner Tabs
tab_bar_edge bottom
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 0.5
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"

# Mouse & Other
focus_follows_mouse yes
